local neotest = require("neotest")

vim.keymap.set("n", "<leader>tt", function()
	neotest.run.run()
end, { desc = "Run nearest test" })
vim.keymap.set("n", "<leader>tf", function()
	neotest.run.run(vim.fn.expand("%"))
end, { desc = "Run current file" })
vim.keymap.set("n", "<leader>td", function()
	neotest.run.run({ strategy = "dap" })
end, { desc = "Debug nearest test" })
vim.keymap.set("n", "<leader>tS", function()
	neotest.run.stop()
end, { desc = "Stop test run" })

vim.keymap.set("n", "<leader>ts", function()
	neotest.summary.toggle()
end, { desc = "Toggle summary panel" })
vim.keymap.set("n", "<leader>to", function()
	neotest.output.open({ enter = true })
end, { desc = "Show test output" })
vim.keymap.set("n", "<leader>tO", function()
	neotest.output_panel.toggle()
end, { desc = "Toggle output panel" })

vim.keymap.set("n", "<leader>tw", function()
	neotest.watch.toggle(vim.fn.expand("%"))
end, { desc = "Watch current file" })
vim.keymap.set("n", "<leader>ta", function()
	neotest.run.attach()
end, { desc = "Attach to running test" })

vim.keymap.set("n", "[t", function()
	neotest.jump.prev({ status = "failed" })
end, { desc = "Jump to prev failed test" })
vim.keymap.set("n", "]t", function()
	neotest.jump.next({ status = "failed" })
end, { desc = "Jump to next failed test" })
